### ISSUE TITLE
Task 10 -  Data visualisation

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/HackerSkills#55]
You need to get a dataset and do its visualisation.
30 points if the visualisation is done on a downloaded data set
50 points if the visualisation is done by first creating a dataset by yourself using scraping.

**Comment by mubaris** [comment]
Why was this closed?

**Comment by gauthamzz** [comment]
its too vauge, will make it more precise and open again.

**Comment by mubaris** [comment]
We'll do this in https://github.com/mubaris/dataviz-gallery :stuck_out_tongue:

**Comment by Anupam-dagar** [comment]
@mubaris triggered :stuck_out_tongue:

**Comment by mubaris** [comment]
I mean, we'll have all viz in one place 😛

**Comment by gauthamzz** [comment]
submit application,we will consider adding your project 😄

**Comment by Jigar3** [comment]
I created a data visualisation script for ohlc graphs depicting stock prices of maruti suzuki in BSE.

**Comment by mubaris** [comment]
@Jigar3 Add it in https://github.com/mubaris/dataviz-gallery
