### ISSUE TITLE
Task 10 - linear regression 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/HackerSkills#62]
Apply machine learning method linear regression on any dataset with two values . The graph generated should also be added in the pr. If you are using python, try using jupyter notebook

**Comment by Jigar3** [comment]
Any relevant links you might wanna share that might help

**Comment by gauthamzz** [comment]
this issue is tranfered to the new repo https://github.com/opencode18/X-labs which focus only on Machine learning .

@Jigar3 you can find great things on internet, my personal fav is sklearn
